import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Playfair_Display, Montserrat, Lora } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marinali Rooms",
  description: "Generated by create next app",
};

import { SettingsService } from "@/lib/services/settingsService";
import Providers from "./providers";

import { Toaster } from "sonner";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await SettingsService.getSettings();

  const primaryColor = settings.primaryColor;
  const secondaryColor = settings.secondaryColor;
  const backgroundColor = settings.backgroundColor;
  const textColor = settings.textColor;
  const fontFamily = settings.fontFamily;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${playfair.variable} ${montserrat.variable} ${lora.variable} antialiased`}
      style={{
        // @ts-ignore
        "--primary-color": primaryColor,
        "--secondary-color": secondaryColor,
        "--background": backgroundColor,
        "--background-color": backgroundColor,
        "--foreground": textColor,
        "--popover": backgroundColor,
        "--popover-foreground": textColor,
        "--font-primary": fontFamily,
      }}
    >
      <body className="min-h-screen flex flex-col">
        <Providers>
          {children}
          <Toaster position="top-center" richColors />
        </Providers>
      </body>
    </html>
  );
}
